// <auto-generated />
using System;
using Graphene_Group_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Graphene.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117020307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Graphene_Group_Project.Data.Entities.Alert", b =>
                {
                    b.Property<long>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AlertId"));

                    b.Property<long?>("FrameId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxPressure")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PixelsAboveThr")
                        .HasColumnType("int");

                    b.Property<string>("RegionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Severity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("TriggeredUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AlertId");

                    b.HasIndex("FrameId");

                    b.HasIndex("PatientId", "TriggeredUtc");

                    b.HasIndex("Status", "Severity");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Graphene_Group_Project.Data.Entities.DataFile", b =>
                {
                    b.Property<long>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FileId"));

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FirstTimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastTimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.HasIndex("PatientId", "FilePath")
                        .IsUnique();

                    b.ToTable("DataFiles");
                });

            modelBuilder.Entity("Graphene_Group_Project.Data.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("PatientId");

                    b.HasIndex("ExternalUserId")
                        .IsUnique()
                        .HasFilter("[ExternalUserId] IS NOT NULL");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Graphene_Group_Project.Data.Entities.PressureFrame", b =>
                {
                    b.Property<long>("FrameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FrameId"));

                    b.Property<DateTime?>("CapturedUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ContactAreaPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<int>("FrameIndex")
                        .HasColumnType("int");

                    b.Property<byte>("Height")
                        .HasColumnType("tinyint");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PeakPressure")
                        .HasColumnType("int");

                    b.Property<int?>("PixelsAboveThr")
                        .HasColumnType("int");

                    b.Property<byte>("Width")
                        .HasColumnType("tinyint");

                    b.HasKey("FrameId");

                    b.HasIndex("FileId");

                    b.HasIndex("PatientId", "CapturedUtc");

                    b.HasIndex("PatientId", "FileId", "FrameIndex")
                        .IsUnique();

                    b.ToTable("PressureFrames");
                });

            modelBuilder.Entity("Graphene_Group_Project.Data.Entities.Alert", b =>
                {
                    b.HasOne("Graphene_Group_Project.Data.Entities.PressureFrame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId");

                    b.HasOne("Graphene_Group_Project.Data.Entities.Patient", "Patient")
                        .WithMany("Alerts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Graphene_Group_Project.Data.Entities.DataFile", b =>
                {
                    b.HasOne("Graphene_Group_Project.Data.Entities.Patient", "Patient")
                        .WithMany("Files")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Graphene_Group_Project.Data.Entities.PressureFrame", b =>
                {
                    b.HasOne("Graphene_Group_Project.Data.Entities.DataFile", "File")
                        .WithMany("Frames")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graphene_Group_Project.Data.Entities.Patient", "Patient")
                        .WithMany("Frames")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Graphene_Group_Project.Data.Entities.DataFile", b =>
                {
                    b.Navigation("Frames");
                });

            modelBuilder.Entity("Graphene_Group_Project.Data.Entities.Patient", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Files");

                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
